# Generated by Django 4.2.5 on 2023-09-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
