# Generated by Django 4.2.5 on 2023-09-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
