# Generated by Django 4.2.5 on 2023-09-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0004_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
