# Generated by Django 4.2.5 on 2023-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executive', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=50)),
                ('spvs_rating', models.IntegerField()),
                ('spvs_interp', models.CharField(max_length=50)),
                ('stud_rating', models.IntegerField()),
                ('stud_interp', models.CharField(max_length=50)),
                ('peer_rating', models.IntegerField()),
                ('peer_interp', models.CharField(max_length=50)),
                ('self_rating', models.IntegerField()),
                ('self_interp', models.CharField(max_length=50)),
            ],
        ),
    ]
