# Generated by Django 4.2.6 on 2023-10-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableone',
            old_name='faculty_number',
            new_name='faculty_num',
        ),
    ]
