# Generated by Django 4.2.5 on 2023-09-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0007_alter_tableone_peer_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='peer_interp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='self_interp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='spvs_interp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='stud_interp',
            field=models.CharField(max_length=20),
        ),
    ]
