# Generated by Django 4.2.6 on 2023-11-19 13:04

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_no', models.CharField(max_length=10)),
                ('training_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('training_date', models.CharField(max_length=120)),
                ('training_time', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
