# Generated by Django 5.0.1 on 2024-01-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0003_auto_20240115_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('training_title', models.CharField(max_length=100)),
            ],
        ),
    ]
