# Generated by Django 4.2.6 on 2023-11-20 11:38

from django.db import migrations

def insert_data(apps, schema_editor):
    TableThree = apps.get_model('executive', 'TableThree')
    data = [
        ["Abalos, Karl Christian D."    , "15:30" , "16:30" , "Effective Teaching Strategies"],
        ["Aquino, Rodolfo Y.  Jr."      , "15:30" , "16:30" , "Effective Teaching Strategies"],
        ["Dolorosa, Rodrigo S., DEM"    , "15:30" , "16:30" , "Effective Teaching Strategies"],
        ["Fernandez, Alma C."           , "15:30" , "16:30" , "Effective Teaching Strategies"],
        ["Oliquino, Joanna Marie DC."   , "15:30" , "16:30" , "Effective Teaching Strategies"],

        ["Fulleros, Jorgen Z."          , "10:00" , "11:30" , "Technology Integration"],
        ["Fabela, Noel F."              , "10:00" , "11:30" , "Technology Integration"],
        ["Bernardino, Girlie F."        , "10:00" , "11:30" , "Technology Integration"],
        ["Cipriano, Erwin"              , "10:00" , "11:30" , "Technology Integration"],
        ["De Leon, Celeste L."          , "10:00" , "11:30" , "Technology Integration"],
        
        ["Umali, Antonius C., DPA"      , "15:30" , "16:30" , "Research Skills"],
        ["Soberano, Maricar O."         , "15:30" , "16:30" , "Research Skills"],
        ["Odpaga, Ernesto J., Jr."      , "15:30" , "16:30" , "Research Skills"],
        ["Gardon, Harold Q."            , "15:30" , "16:30" , "Research Skills"],
        ["Gulmatico, Esther S., Ph.D."  , "15:30" , "16:30" , "Research Skills"],
        
        ["Cruz, Mary Grace I."          , "15:30" , "16:30" , "Inclusive Teaching"],
        ["Escober, Rosicar E., Ph.D."   , "15:30" , "16:30" , "Inclusive Teaching"],
        ["Escober, Ain Gueul E."        , "15:30" , "16:30" , "Inclusive Teaching"],
        ["Gutierrez, Jaime Jr. P."      , "15:30" , "16:30" , "Inclusive Teaching"],
        ["Domingo, Keinaz"              , "15:30" , "16:30" , "Inclusive Teaching"],
        
        ["Roxas, Rommel Y."             , "10:00" , "11:30" , "Communication Skills"],
        ["Pineda, Jose Gil C."          , "10:00" , "11:30" , "Communication Skills"],
        ["Leynes, Jerome Chrstopher G." , "10:00" , "11:30" , "Communication Skills"],
        ["Morales, Sheryl R."           , "10:00" , "11:30" , "Communication Skills"],
        ["Garcia, Maita C."             , "10:00" , "11:30" , "Communication Skills"],
        
        ["Calingasan, Francisco S."     , "09:30" , "10:30" , "Leadership and Management"],
        ["Bernardino, Abraham Seth R."  , "09:30" , "10:30" , "Leadership and Management"],
        ["Clenuar, Ricardo H."          , "09:30" , "10:30" , "Leadership and Management"],
        ["Aribon, Mark Anthony R. III"  , "09:30" , "10:30" , "Leadership and Management"],
        ["Caturay, Norberto V., DEM"    , "09:30" , "10:30" , "Leadership and Management"],
        
        ["Gardon, Harold Q."            , "09:30" , "10:30" , "Professional Networking"],
        ["Doromal, Cherry M."           , "09:30" , "10:30" , "Professional Networking"],
        ["Delmo, Elijah Paul B. "       , "09:30" , "10:30" , "Professional Networking"],
        ["Cecogo, Nieva M."             , "09:30" , "10:30" , "Professional Networking"],
        ["Baltazar, Mary Ann Micah R."  , "09:30" , "10:30" , "Professional Networking"],
    ]
    for item in data:
        TableThree.objects.create(
            faculty_name=item[0],
            time_in=item[1],
            time_out=item[2],
            training_title=item[3],
        )

class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0004_tablethree'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
