# Generated by Django 4.2.6 on 2023-11-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0005_auto_20231120_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsrch_author', models.CharField(max_length=100)),
                ('rsrch_title', models.CharField(max_length=200)),
                ('rsrch_year', models.DateField()),
                ('rsrch_publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
