# Generated by Django 5.0.1 on 2024-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0005_auto_20240115_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsrch_author', models.CharField(max_length=100)),
                ('rsrch_title', models.CharField(max_length=200)),
                ('rsrch_year', models.DateField()),
                ('rsrch_publisher', models.CharField(max_length=100)),
                ('rsrch_category', models.CharField(max_length=100)),
                ('rsrch_author_type', models.CharField(max_length=50)),
            ],
        ),
    ]
