# Generated by Django 5.0.1 on 2024-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0007_auto_20240115_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_faculty_name', models.CharField(max_length=50)),
                ('merit_faculty_status', models.CharField(max_length=50)),
                ('merit_ave_dept_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('merit_rsrch_publish', models.CharField(max_length=200)),
                ('merit_training_attended', models.CharField(max_length=100)),
                ('merit_promotion', models.BooleanField()),
            ],
        ),
    ]
