# Generated by Django 4.2.6 on 2023-11-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0007_tablefive_rename_faculty_number_tableone_faculty_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableone',
            old_name='faculty_num',
            new_name='faculty_number',
        ),
    ]
