# Generated by Django 4.2.6 on 2023-11-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0007_rename_faculty_number_tableone_faculty_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_no', models.CharField(max_length=10)),
                ('training_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('training_date', models.DateField()),
                ('training_time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
