# Generated by Django 4.2.6 on 2023-11-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0008_tablethree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablethree',
            name='training_date',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='training_time',
            field=models.CharField(max_length=120),
        ),
    ]
