# Generated by Django 4.2.6 on 2023-11-22 13:04

from django.db import migrations

def insert_data(apps, schema_editor):
    TableFive = apps.get_model('executive', 'TableFive')

    data = [
        ["Abalos, Karl Christian D."        , "Regular Non-Designee" , "4.31"   , "12" , "3" , False],
        ["Aquino, Rodolfo Y.  Jr."          , "Regular Non-Designee" , "3.87"   , "8"  , "4" , False],
        ["Aribon, Mark Anthony R. III"      , "Regular Non-Designee" , "3.75"   , "4"  , "1" , False],
        ["Bactasa, Melanie F."              , "Regular Non-Designee" , "4.21"   , "6"  , "2" , False],
        ["Baltazar, Mary Ann Micah R., CPA" , "Regular Non-Designee" , "4.0"    , "5"  , "4" , False],
        ["Banate, Richard B., CPA"          , "Regular Non-Designee" , "4.42"   , "86" , "3" , False],
        ["Bernardino, Abraham Seth R."      , "Regular Non-Designee" , "4.1"    , "34" , "3" , False],
        ["Bernardino, Girlie F."            , "Regular Non-Designee" , "3.99"   , "6"  , "1" , False],
        ["Bulawit, Berna A."                , "Regular Non-Designee" , "4.56"   , "3"  , "5" , False],
        ["Calingasan, Francisco S."         , "Regular Non-Designee" , "4.32"   , "0"  , "2" , False],
        ["Castillo, Eleazar E."             , "Regular Non-Designee" , "4.11"   , "0"  , "4" , False],
        ["Caturay, Norberto V., DEM"        , "Regular Non-Designee" , "4.25"   , "45" , "1" , False],
        ["Cecogo, Nieva M."                 , "Regular Non-Designee" , "3.45"   , "5"  , "4" , False],
        ["Cipriano, Erwin"                  , "Regular Non-Designee" , "3.78"   , "8"  , "2" , False],
        ["Clenuar, Ricardo H."              , "Regular Non-Designee" , "4.32"   , "2"  , "1" , False],
        ["Cruz, Mary Grace I."              , "Regular Non-Designee" , "4.95"   , "12" , "1" , False],
        ["De Leon, Celeste L."              , "Regular Non-Designee" , "3.75"   , "2"  , "1" , False],
        ["Delmo, Elijah Paul B."            , "Regular Non-Designee" , "3.2"    , "1"  , "1" , False],
        ["Dolorosa, Rodrigo S., DEM"        , "Regular Non-Designee" , "4.3"    , "0"  , "1" , False],
        ["Domingo, Keinaz"                  , "Regular Non-Designee" , "3.47"   , "1"  , "1" , False],
        ["Doromal, Cherry M."               , "Regular Non-Designee" , "4.67"   , "1"  , "1" , False],
        ["Doromal, Roberto B."              , "Regular Non-Designee" , "4.12"   , "1"  , "3" , False],
        ["Dungca, Leah A."                  , "Regular Non-Designee" , "4.23"   , "1"  , "2" , False],
        ["Escober, Ain Gueul E."            , "Regular Non-Designee" , "4.34"   , "1"  , "4" , False],
        ["Escober, Rosicar E., Ph.D."       , "Regular Non-Designee" , "4.44"   , "4"  , "1" , False],
        ["Esguerra, Firmo A."               , "Regular Non-Designee" , "4.45"   , "5"  , "4" , False],
        ["Esparagoza, Cherrylyn P."         , "Regular Non-Designee" , "4.6"    , "2"  , "1" , False],
        ["Estella, Zandro T."               , "Regular Non-Designee" , "4.2"    , "3"  , "7" , False],
        ["Fabela, Noel F."                  , "Regular Non-Designee" , "4.45"   , "1"  , "3" , False],
        ["Fernandez, Alma C."               , "Regular Non-Designee" , "4.3"    , "3"  , "1" , False],
        ["Fulleros, Richard M."             , "Regular Non-Designee" , "4.85"   , "3"  , "1" , False],
        ["Fulleros, Jorgen Z."              , "Regular Non-Designee" , "4.65"   , "1"  , "2" , False],
        ["Gabasa, Asuncion V."              , "Regular Non-Designee" , "4.44"   , "3"  , "4" , False],
        ["Garcia, Maita C."                 , "Regular Non-Designee" , "4.43"   , "0"  , "1" , False],
        ["Gardon, Harold Q."                , "Regular Non-Designee" , "4.23"   , "0"  , "3" , False],
        ["Gatan, Leslie O."                 , "Regular Non-Designee" , "4.67"   , "0"  , "3" , False],
        ["Gatchalian, Irynne P."            , "Regular Non-Designee" , "4.90"   , "0"  , "1" , False],
        ["Gulmatico, Esther S., Ph.D."      , "Regular Non-Designee" , "4.64"   , "0"  , "3" , False],
        ["Gutierrez, Jaime Jr. P."          , "Regular Non-Designee" , "4.33"   , "0"  , "3" , False],
        ["Isip, John Robert F."             , "Regular Non-Designee" , "4.98"   , "0"  , "3" , False],
        ["Lara, Erwin Vicman"               , "Regular Non-Designee" , "4.43"   , "0"  , "1" , False],
        ["Leynes, Jerome Chrstopher G."     , "Regular Non-Designee" , "4.86"   , "0"  , "3" , False],
        ["Monzon, Demelyn E. Ph.D"          , "Regular Non-Designee" , "4.57"   , "0"  , "2" , False],
        ["Monzon, Kezaiah M."               , "Regular Non-Designee" , "4.78"   , "0"  , "1" , False],
        ["Morales, Sheryl R."               , "Regular Non-Designee" , "4.77"   , "0"  , "0" , False],
        ["Odpaga, Ernesto J., Jr."          , "Regular Non-Designee" , "4.4"    , "3"  , "1" , False],
        ["Oliquino, Joanna Marie DC."       , "Regular Non-Designee" , "4.23"   , "3"  , "1" , False],
        ["Pineda, Jose Gil C."              , "Regular Non-Designee" , "4.17"   , "1"  , "1" , False],
        ["Roxas, Rommel Y."                 , "Regular Non-Designee" , "4.0"    , "8"  , "1" , False],
        ["Servigon, Cleotilde B."           , "Regular Non-Designee" , "4.21"   , "9"  , "1" , False],
        ["Soberano, Maricar O."             , "Regular Non-Designee" , "4.21"   , "14" , "1" , False],
        ["Soberano, Philip SJ."             , "Regular Non-Designee" , "4.22"   , "3"  , "1" , False],
        ["Umali, Antonius C., DPA"          , "Regular Non-Designee" , "4.1"    , "15" , "1" , False]
    ]

    for item in data:
        TableFive.objects.create(
            merit_faculty_name=item[0],
            merit_faculty_status=item[1],
            merit_ave_dept_rate=item[2],
            merit_rsrch_publish=item[3],
            merit_training_attended=item[4],
            merit_promotion=item[5],
        )

class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0008_tablefive'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]