# Generated by Django 4.2.6 on 2023-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0008_rename_faculty_num_tableone_faculty_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableone',
            name='faculty_number',
        ),
        migrations.AddField(
            model_name='tableone',
            name='faculty_num',
            field=models.IntegerField(default=0),
        ),
    ]
