# Generated by Django 4.2.6 on 2023-11-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0011_auto_20231124_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_faculty', models.CharField(max_length=50)),
                ('eval_type', models.CharField(max_length=20)),
                ('eval_person', models.CharField(max_length=20)),
                ('eval_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('eval_comms', models.CharField(max_length=900)),
            ],
        ),
    ]
