# Generated by Django 5.0.1 on 2024-01-15 16:25

from django.db import migrations

def insert_data(apps, schema_editor):
    TableEight = apps.get_model('executive', 'TableEight')

    data = [
        ["Abalos, Karl Christian D."        , "Teaching Excellence Award"                            , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Aquino, Rodolfo Y.  Jr."          , "Research Achievement Award"                          , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Aribon, Mark Anthony R. III"      , "Service to the Community Award"                      , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Bactasa, Melanie F."              , "Outstanding Mentorship Award"                        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Baltazar, Mary Ann Micah R., CPA" , "Innovative Curriculum Development Award"             , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Banate, Richard B., CPA"          , "Faculty Leadership Award"                            , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Bernardino, Abraham Seth R."      , "Distinguished Professorship"                         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Bernardino, Girlie F."            , "Early Career Faculty Award"                          , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Bulawit, Berna A."                , "Lifetime Achievement Award"                          , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Calingasan, Francisco S."         , "Excellence in Online Teaching Award"                 , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Castillo, Eleazar E."             , "Faculty Diversity Award"                             , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Caturay, Norberto V., DEM"        , "Excellence in Advising Award"                        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Cecogo, Nieva M."                 , "Publication of the Year Award"                       , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Cipriano, Erwin"                  , "Faculty Research Fellowship"                         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Clenuar, Ricardo H."              , "International Educator Award"                        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Cruz, Mary Grace I."              , "Faculty Excellence in Civic Engagement Award"        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["De Leon, Celeste L."              , "Excellence in Assessment Award"                      , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Delmo, Elijah Paul B."            , "Faculty Collaboration Award"                         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Dolorosa, Rodrigo S., DEM"        , "Faculty Sustainability Award"                        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Domingo, Keinaz"                  , "Excellence in Technology Integration Award"          , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Doromal, Cherry M."               , "Excellence in Student Support Services Award"        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Doromal, Roberto B."              , "Faculty Writing Award"                               , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Dungca, Leah A."                  , "Excellence in Interdisciplinary Research Award"      , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Escober, Ain Gueul E."            , "Community Engagement and Outreach Award"             , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Escober, Rosicar E., Ph.D."       , "Faculty Excellence in Global Education Award"        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Esguerra, Firmo A."               , "Faculty Excellence in Creative Arts Award"           , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Esparagoza, Cherrylyn P."         , "Inclusive Teaching Award"                            , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Estella, Zandro T."               , "Faculty Development Grant"                           , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Fabela, Noel F."                  , "Faculty Excellence in Public Health Award"           , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Fernandez, Alma C."               , "Excellence in Professional Development Award"        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Fulleros, Richard M."             , "Faculty Excellence in Leadership Development Award"  , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Fulleros, Jorgen Z."              , "Faculty Innovation in Health Sciences Award"         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Gabasa, Asuncion V."              , "Emerging Scholar Award"                              , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Garcia, Maita C."                 , "Faculty Diversity and Inclusion Leadership Award"    , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Gardon, Harold Q."                , "Excellence in Faculty Advising and Mentoring Award"  , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Gatan, Leslie O."                 , "Faculty Excellence in Ethics Education Award"        , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Gatchalian, Irynne P."            , "Faculty Excellence in Social Justice Award"          , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Gulmatico, Esther S., Ph.D."      , "Faculty Award for Excellence in Entrepreneurship"    , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Gutierrez, Jaime Jr. P."          , "Excellence in Faculty Wellness Award"                , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Isip, John Robert F."             , "Faculty Excellence in Sports Coaching"               , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Lara, Erwin Vicman"               , "Faculty Excellence in Clinical Practice Award"       , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Leynes, Jerome Chrstopher G."     , "Faculty Excellence in Communication Studies"         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Monzon, Demelyn E. Ph.D"          , "Outstanding Faculty in History Award"                , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Monzon, Kezaiah M."               , "Excellence in Psychology Teaching"                   , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Morales, Sheryl R."               , "Faculty Award for Excellence in Mathematics"         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Odpaga, Ernesto J., Jr."          , "Faculty Excellence in Environmental Science"         , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Oliquino, Joanna Marie DC."       , "Faculty Excellence in Engineering Research"          , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Pineda, Jose Gil C."              , "Faculty Excellence in Linguistics"                   , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Roxas, Rommel Y."                 , "Faculty Award in Business Ethics"                    , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Servigon, Cleotilde B."           , "Excellence in Music Education"                       , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Soberano, Maricar O."             , "Faculty Excellence in Leadership Development Award"  , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Soberano, Philip SJ."             , "Excellence in Assessment Award"                      , "2023-11-19"      , "Teaching Excellence"    , "Verified"],
        ["Umali, Antonius C., DPA"          , "Outstanding Mentorship Award"                        , "2023-11-19"      , "Teaching Excellence"    , "Verified"]
    ]

    for item in data:
        TableEight.objects.create(
            awards_faculty  = item[0],
            awards_title    = item[1],
            awards_date     = item[2],
            awards_type     = item[3],
            awards_status   = item[4], 
    )

class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0014_tableeight'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]