# Generated by Django 5.0.1 on 2024-01-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0015_auto_20240116_0025'),
    ]

    operations = [
        migrations.DeleteModel('TableOne'),
    ]
