# Generated by Django 4.2.6 on 2023-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0015_auto_20231127_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableNine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_faculty', models.CharField(max_length=50)),
                ('awards_title', models.CharField(max_length=50)),
                ('awards_date', models.DateField()),
                ('awards_type', models.CharField(max_length=50)),
                ('awards_status', models.CharField(max_length=300)),
            ],
        ),
    ]
